import { readFileSync, writeFileSync } from 'node:fs';
import { SOURCES } from '../src/data/sources.ts';
import { quoteFound } from '../src/data/quote.ts';
import { AMENDMENTS } from '../src/data/amendments.ts';
import { CLAUSES } from '../src/data/clauses.ts';
import { GRIEVANCES } from '../src/data/grievances.ts';
import { FOUNDERS } from '../src/data/founders.ts';
import { WHO_SAID } from '../src/data/whoSaid.ts';
import type { Quoted } from '../src/data/types.ts';

const items: (Quoted & { label: string })[] = [
  ...AMENDMENTS.map(a => ({ ...a, label: `Amendment ${a.n}` })),
  ...CLAUSES.map(c => ({ ...c, label: `Unfinished: ${c.title}` })),
  ...GRIEVANCES.map((g, i) => ({ ...g, label: `Grievance ${i + 1}` })),
  ...FOUNDERS.map(f => ({ ...f, label: `Founder: ${f.speaker}` })),
  ...WHO_SAID.map((w, i) => ({ ...w, label: `Who Said It ${i + 1}` })),
];
const url = Object.fromEntries(SOURCES.map(s => [s.id, s.url]));
const text = Object.fromEntries(SOURCES.map(s => [s.id, readFileSync(`sources-cache/${s.id}.txt`, 'utf8')]));
const rows = items.map(it => ({ ...it, ok: !!text[it.source] && quoteFound(it.quote, text[it.source]) }));
const esc = (s: string) => s.replace(/\|/g, '\\|');
const ok = rows.filter(r => r.ok).length;
writeFileSync('docs/sources.md', [
  '# Source verification', '',
  `Generated by \`npm run verify-quotes\`. **${ok}/${rows.length} quotes verified** word for word against \`sources-cache/\`.`, '',
  '| Status | Item | Source | Section | Quote |', '|---|---|---|---|---|',
  ...rows.map(r => `| ${r.ok ? '✅ verified' : '❌ NOT FOUND'} | ${esc(r.label)} | [${r.source}](${url[r.source]}) | ${esc(r.section)} | ${esc(r.quote)} |`),
].join('\n') + '\n');
for (const r of rows.filter(r => !r.ok)) console.error(`NOT FOUND [${r.source}] ${r.label}: ${r.quote}`);
console.log(`${ok}/${rows.length} verified`);
process.exit(ok === rows.length ? 0 : 1);
